let booksDB = [
    {
        id :1 ,
        title :'title',
        author:'mystery',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :2 ,
        title :'title',
        author:'mystery',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :3,
        title :'title',
        author:'mystery',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :4 ,
        title :'title',
        author:'horror',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :5 ,
        title :'title',
        author:'horror',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :6 ,
        title :'title',
        author:'romance',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :7,
        title :'title',
        author:'romance',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :8 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },

    {
        id :9 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :10 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },

    {
        id :11,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :12 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :13,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :14 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },

    {
        id :15 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :16 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },

    {
        id :17,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
    {
        id :18 ,
        title :'title',
        author:'author',
        desc: 'Lorem ipsm , dolor sit amet consectetur.',
        ImageUrl: 'images/book-image.jpg',
        like:0,
    },
];